import 'app_routes.dart';

class AppStatic {
  static Map<String, String> map = {
    AppRoutes.baladiaInfo: "بيانات البلدية",
    AppRoutes.nations: "انواع الجنسيات",
    AppRoutes.dissents: "أنواع المخالفات",
    AppRoutes.jobs: "أنواع الوظائف",
    AppRoutes.badalCountries: "تصنيف الدول حسب فئات البدل",
    AppRoutes.badal: "بدل الانتداب",
    AppRoutes.empDegrees: "سلم درجات الموظفين",
    AppRoutes.empDegreesWorker: "سلم درجات العمال",
    AppRoutes.parts: "أنواع الأقسام",
    // AppRoutes.holidayType: "أنواع الإجازات",
    AppRoutes.users: "المستخدمين",
    AppRoutes.signatures: "إدارة التوقيعات",
    AppRoutes.dowraSearch: "الإستعلام عن الدورات",
    AppRoutes.endSearch: "الاستعلام عن إنهاء خدمة",
    AppRoutes.entedabSearch: "الإستعلام عن إنتداب",
    AppRoutes.hasmiatSearch: "الإستعلام عن حسميات",
    AppRoutes.holidaySearch: "الإستعلام عن إجازة",
    AppRoutes.kashfTepySearch: "الإستعلام عن كشف طبي",
    AppRoutes.mobashraSearch: "الإستعلام عن مباشرة",
    AppRoutes.mokhalfatSearch: "الإستعلام عن مخالفات",
    AppRoutes.takleefSearch: "الإستعلام عن خارح دوام",
    AppRoutes.taeenSearch: "الاستعلام عن قرار تعيين",
    AppRoutes.tarqeaSearch: "الاستعلام عن ترقية",
    AppRoutes.passportSearch: "الاستعلام عن إقرار جواز سفر",
    AppRoutes.tafweedSearch: "الاستعلام عن تفويض",
    AppRoutes.employeeSearch: "الإستعلام عن موظف",
    AppRoutes.eqrarSearch: "الاستعلام عن إقرار",
    AppRoutes.addTafweed: "تفويض",
    AppRoutes.addDowra: "بيان دورة موظف",
    AppRoutes.addEnd: "إنهاء خدمة",
    AppRoutes.addEntedab: "بيانات الإنتداب",
    AppRoutes.addEqrar: "إقرار موظف",
    AppRoutes.addHasmiat: "بيانات الحسميات",
    AppRoutes.addHoliday: "بيانات الإجازات",
    AppRoutes.addKashfTepy: "طلب كشف طبي",
    AppRoutes.addMobashra: "قرار مباشرة",
    AppRoutes.addMokhalfat: "بيانات المخالفات",
    AppRoutes.addTaeen: "قرار تعيين",
    AppRoutes.addTarqea: "ترقية موظف",
    AppRoutes.addPassport: "إقرار استلام جواز سفر",
    AppRoutes.addTakleef: "بيانات خارح دوام",
    AppRoutes.addEmployee: "بيانات الوظائف الأساسية",
    AppRoutes.mosaeerSalary: "مسير الرواتب",
    AppRoutes.entedabReport: "تقرير الإنتدابات",
    AppRoutes.takleefReport: "تقرير خارج دوام",
    AppRoutes.hasmiatReport: "تقرير الحسميات",
    AppRoutes.mokhalfatReport: "تقرير المخالفات",
    AppRoutes.holidayReport: "تقرير الإجازات",
    AppRoutes.kashfTepyReport: "تقرير الكشف الطبي",
    AppRoutes.mobashraReport: "تقرير المباشرة",
    AppRoutes.tafweedReport: "تقرير التفويض",
    AppRoutes.endReport: "تقرير إنهاء الخدمة",
    AppRoutes.eqrarReport: "تقرير الإقرار",
    AppRoutes.employeeReport: "تقرير بيانات الموظفين",
    AppRoutes.pdfViewer: "pdfViewer",
  };
}
